# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qt_Janela(object):
    def setupUi(self, Qt_Janela):
        Qt_Janela.setObjectName("Qt_Janela")
        Qt_Janela.resize(877, 521)
        self.centralwidget = QtWidgets.QWidget(Qt_Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.472, y2:1, stop:0 rgba(0, 234, 19, 218), stop:0.494318 rgba(6, 218, 13, 207), stop:1 rgba(0, 151, 11, 214));\n"
"border: 10px solid rgb(26, 113, 0);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_buscar_path = QtWidgets.QPushButton(self.frame)
        self.pb_buscar_path.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_buscar_path.setFont(font)
        self.pb_buscar_path.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 5px; \n"
"border: 3px solid rgb(19, 158, 12);\n"
"}")
        self.pb_buscar_path.setAutoRepeat(False)
        self.pb_buscar_path.setObjectName("pb_buscar_path")
        self.gridLayout.addWidget(self.pb_buscar_path, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pb_converter = QtWidgets.QPushButton(self.frame)
        self.pb_converter.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Naskh Arabic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_converter.setFont(font)
        self.pb_converter.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius: 5px; \n"
"border: 3px solid rgb(19, 158, 12);\n"
"}")
        self.pb_converter.setObjectName("pb_converter")
        self.gridLayout.addWidget(self.pb_converter, 2, 2, 1, 1)
        self.lb_caminho = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_caminho.setFont(font)
        self.lb_caminho.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"border: 5px solid rgb(19, 158, 12);\n"
"}")
        self.lb_caminho.setObjectName("lb_caminho")
        self.gridLayout.addWidget(self.lb_caminho, 1, 0, 1, 1)
        self.le_caminho = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.le_caminho.setFont(font)
        self.le_caminho.setObjectName("le_caminho")
        self.gridLayout.addWidget(self.le_caminho, 1, 1, 1, 1)
        self.lb_formato = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lb_formato.setFont(font)
        self.lb_formato.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"border: 5px solid rgb(19, 158, 12);\n"
"}")
        self.lb_formato.setObjectName("lb_formato")
        self.gridLayout.addWidget(self.lb_formato, 2, 0, 1, 1)
        self.le_formato = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.le_formato.setFont(font)
        self.le_formato.setStyleSheet("")
        self.le_formato.setObjectName("le_formato")
        self.gridLayout.addWidget(self.le_formato, 2, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("border: 3px solid rgb(19, 158, 12);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"border: 0;\n"
"background-color: 0;\n"
"}")
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.pb_play = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_play.setFont(font)
        self.pb_play.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.pb_play.setObjectName("pb_play")
        self.gridLayout_3.addWidget(self.pb_play, 6, 2, 1, 1)
        self.pb_stop = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_stop.setFont(font)
        self.pb_stop.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.pb_stop.setObjectName("pb_stop")
        self.gridLayout_3.addWidget(self.pb_stop, 6, 4, 1, 1)
        self.pb_pause = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_pause.setFont(font)
        self.pb_pause.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.pb_pause.setObjectName("pb_pause")
        self.gridLayout_3.addWidget(self.pb_pause, 6, 3, 1, 1)
        self.videoWidget = QtWidgets.QWidget(self.frame_2)
        self.videoWidget.setMinimumSize(QtCore.QSize(640, 360))
        self.videoWidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.videoWidget.setObjectName("videoWidget")
        self.gridLayout_3.addWidget(self.videoWidget, 2, 2, 1, 3)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 3)
        self.verticalLayout.addWidget(self.frame)
        Qt_Janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(Qt_Janela)
        QtCore.QMetaObject.connectSlotsByName(Qt_Janela)

    def retranslateUi(self, Qt_Janela):
        _translate = QtCore.QCoreApplication.translate
        Qt_Janela.setWindowTitle(_translate("Qt_Janela", "MainWindow"))
        self.pb_buscar_path.setText(_translate("Qt_Janela", "  Buscar Caminho  "))
        self.pb_converter.setText(_translate("Qt_Janela", "CONVERTER"))
        self.lb_caminho.setText(_translate("Qt_Janela", "Caminho do Vídeo: "))
        self.le_caminho.setPlaceholderText(_translate("Qt_Janela", "Caminho do video ..."))
        self.lb_formato.setText(_translate("Qt_Janela", "Novo formato:"))
        self.le_formato.setPlaceholderText(_translate("Qt_Janela", "MP4, AVI, MKV ..."))
        self.label_4.setText(_translate("Qt_Janela", "Trocar formato de um arquivo de vídeo"))
        self.pb_play.setText(_translate("Qt_Janela", "PLAY"))
        self.pb_stop.setText(_translate("Qt_Janela", "STOP"))
        self.pb_pause.setText(_translate("Qt_Janela", "PAUSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Qt_Janela = QtWidgets.QMainWindow()
    ui = Ui_Qt_Janela()
    ui.setupUi(Qt_Janela)
    Qt_Janela.show()
    sys.exit(app.exec_())
